<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
///var/www/gym/vendor/yiisoft/yii2/messages/es
return [
    
    'id_archive_proof' => 'id_archive_proof',
    'id_payment_account' => 'id_payment_account',
    'id_contract' => 'Contrato',
    'id_status' => 'Estado',
    'id_type_proof' => 'Tipo de Comprovante',
    'create_time' => 'Fecha Creada',
    'update_time' =>  'update_time',
    'label' =>  'label',
    'proof_url' =>  'Archivo',
    'description' => 'Descripción',
    
    
    ];

?>

