<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
///var/www/gym/vendor/yiisoft/yii2/messages/es
return [
        'Bank Account' => 'Cuenta Bancaria',
        'Bank Accounts' => 'Cuenta Bancarias',
        'id_bank_account' => 'id_bank_account',
        'id_contact' => 'Banco',
        'id_type' => 'Tipo',
        'id_status' => 'Estado',
        'id_currency' => 'Moneda',
        'account_name' =>'Nombre de Cuenta',
        'account_number' => 'Numero de Cuenta',
        'opening_balance' => 'Saldo Inicial',
        'current_balance' => 'Saldo Actual',
        'created_date' => 'Fecha Creada',
        'updated_date' => 'Fecha Modificada',
    
        'companyNameValue' => 'Banco',
        'idType.type_name' => 'Tipo',
        'idStatus.status_name' => 'Estado'
       
    ];

?>

