<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
///var/www/gym/vendor/yiisoft/yii2/messages/es
return [
    'Contract' => 'Contrato',
    'Contracts' => 'Contratos',
    'id_contract' => 'id_contract',
    'id_type' => 'Tipo de Contracto',
    'id_status' => 'Estado',
    'id_customer' => 'Cliente',
    'id_supplier' => 'Proveedor',
    'id_service' => 'Servicio',
    'id_periodicity' => 'Periodicidad de Pago',
    'periodicity_number' => 'Cantidad de la Duracción',
    'fee' => 'Cuotas',
    'indeterminate' => 'indeterminate',
    'contract_number' => 'Numero Contrato',
    'date_signature' => 'Fecha Firma',
    'date_opened' => 'Fecha Inicio',
    'date_ended' => 'Fecha Fin',
    'payment_deadline' => 'Dias Limite de Pago',
    'self_renewing' => 'Auto Renovable',
    'contract_self_renewing' => 'contract_self_renewing',
    'consumer' => 'Tipo de Consumo',
    'fixed_amount' => 'Monto Fijo',
    'budgeted_amount' => 'Monto Presupuestado',
    'contract_description' => 'Descripción',
    'third' => 'Terceros',
    
    'dateSignatureValue' => 'Fecha Firma',
    'dateEndedValue' => 'Fecha Fin',
    'dateOpenedValue' => 'Fecha Inicio',
    ];

?>

