<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
///var/www/gym/vendor/yiisoft/yii2/messages/es
return [
    'Person' => 'Persona',
    'People' => 'Personas',
    'id_person' => 'id_person',
    'id_contact' => 'Contacto',
    'id_city' => 'Ciudad',
    'id_marital_status' => 'Estado Civil',
    'person_name' => 'Nombres',
    'last_name' => 'Apellidos',
    'nick_name' => 'Apodo',
    'identity_card' => 'Carnet',
    'nit' => 'Nit',
    'issued' => 'Expedido en',
    'birthday' => 'Cumpleaños',
    'gender' => 'Sexo',
    'photo' => 'Foto',
    
    'Male' =>'Masculino',
    'Female' =>'Femenino',
    'Single' => 'Soltero(a)',
    'Married' => 'Casado(a)',
    'Sapareted' => 'separado(a)',
    'Divorced' => 'Divorsiado(a)',
    'Widowed' => 'Viudo(a)',
    'Living with someone' => 'Viviendo con alguien',
    
    'country' => 'Pais',
    'birthdayValue' => 'Cumpleaños',
    'genderValue' => 'Sexo',
    'maritalStatusValue' => 'Estado Civil',
    
    ];

?>

