<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
///var/www/gym/vendor/yiisoft/yii2/messages/es
return [
    'Proyect' => 'Proyecto',
    'Proyects' => 'Proyectos',
    'id_proyect' => 'Proyecto',
    'id_status' => 'Estado',
    'id_user' => 'id_user',
    'proyect_name' => 'Nombre Proyecto',
    'amount' => 'Monto Total',
    'periodicity_number' => 'Duracción en días',
    'begin_date' =>'Fecha Inicio',
    'end_date' => 'Fecha Fin',
    'created_date' => 'Fecha Creada',
    'updated_date' => 'Fecha Modificada',
       
    ];

?>

