<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
///var/www/gym/vendor/yiisoft/yii2/messages/es
return [
    'Invoice' => 'Factura',
    'Invoices' => 'Facturas',
    'id_invoice' => 'id_invoice',
    'id_billing' => 'Docificación',
    'id_status' =>  'Estado',
    'id_contact' => 'Contacto',
    'id_user' => 'Usuario',
    'id_payment' => 'Pago',
    'invoice_number' => '# Factura',
    'control_code' =>'Código Control',
    'pay_date' => 'Fecha de Pago',
    'pay_time' => 'Hora de Pago',
    'total_amount' => 'Monto',
    
    ];

?>

