<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
///var/www/gym/vendor/yiisoft/yii2/messages/es
return [
    'Payment' => 'Pago',
    'Payments' => 'Pagos',
    'id_payment' => 'id_payment',
    'id_debt' => 'Deuda',
    'id_type' => 'Tipo',
    'id_status' => 'Estado',
    'id_type_payment' => 'Tipo de Pago',
    'id_exchange_rate' =>'Tipo de Cambio',
    'create_time' => 'Fecha Creada',
    'update_time' => 'Fecha Modificada',
    'amount' => 'Monto Cancelado',
    'box_amount' => 'Monto En Caja',
    'change' => 'Vuelto',
    'sales_check' => 'Factura',
    'bank_name' => 'Nombre Banco',
    'check_number' => 'Numero de Tarjeta/Cheque',
    'payment_description' => 'Descripción',
            
    'currency' => 'Moneda',
    'createTimeValue' => 'Fecha Creada',
    'updateTimeValue' => 'Fecha Modificada',
       
    ];

?>

