<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
///var/www/gym/vendor/yiisoft/yii2/messages/es
return [
    'Proyect Person' => 'Proyecto Empleado',
    'Proyects Person' => 'Proyectos Empleados',
    'id_proyect_person' => 'id_proyect_person',
    'id_proyect' => 'id_proyect',
    'id_person' => 'id_person',
    'amount' =>  'Monto',
    'payment_type' => 'Tipo de Pago',
    'created_date' => 'Fecha Creada',
    'updated_date' => 'Fecha Modificada',
       
    ];

?>

